# Resources:
# - https://github.com/maxheld83/ghactions

name: Full build, test and publish
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build the package
    runs-on: ubuntu-latest
    steps:
      - name: Get the rocker image
        uses: docker://rocker/verse
      - name: Check out my own repository
        uses: actions/checkout@v2
      - name: Build the package
        run: |
          make install
          
        

