# Resources:
# - https://github.com/maxheld83/ghactions
# - https://github.com/r-lib/actions/tree/master/examples

name: Full build, test and publish
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, test and publish
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v2
      - name: Build the package
        run: make install
      - name: Test the package
        run: make test
      - name: R CMD check
        run: make check
      - name: Build pkgdown website
        run: make pkgdown
      - name: Update gh-pages
        run: bash .update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/

          
        

