### * Resources:

# - https://github.com/maxheld83/ghactions
# - https://github.com/r-lib/actions/tree/master/examples

### * Setup

name: Full build, test and publish
on:
  push:
    branches:
      - master

### * Jobs
      
jobs:

### ** build
  
  build:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: make install

### ** test
          
  test:
    runs-on: ubuntu-latest
    container: rocker/verse
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: make install
      - name: Test the package
        run: make test

### ** check
        
  check:
    runs-on: ubuntu-latest
    container: rocker/verse
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: make install
      - name: Check the package (R CMD check)
        run: make check

### ** pkgdown
        
  pkgdown:
    runs-on: ubuntu-latest
    container: rocker/verse
    needs: [test, check]
    steps:
      - uses: actions/checkout@v1
      - name: Build the package
        run: make install
      - name: Build the pkgdown website
        run: |
          make pkgdown
          cp .update-gh-pages.sh docs/
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: pkgdown-docs
          path: ./docs/
    
### ** update-gh-pages

  update-gh-pages:
    runs-on: ubuntu-latest
    needs: pkgdown
    steps:
      - uses: actions/checkout@v1
      - run: git checkout gh-pages
      - run: |
          pwd
          ls
          rm -fr ./*
          ls
          git branch -a
      - uses: actions/download-artifact@v1
        with:
          name: pkgdown-docs
          path: .
      - run: |
          pwd
          ls
          git branch -a
          cat .update-gh-pages.sh
          bash .update-gh-pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
