# Resources:
# - https://github.com/maxheld83/ghactions
# - https://github.com/r-lib/actions/tree/master/examples

name: Full build, test and publish
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build the package
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - name: Check out my own repository
        uses: actions/checkout@v2
      - name: Build the package
        run: |
          make install
          
        

